@echo off
setlocal

set "ROOT_DIR=%~dp0"
set "PYVIDEOTRANS_PYTHON=%LOCALAPPDATA%\Programs\Python\Python310\python.exe"

if not exist "%PYVIDEOTRANS_PYTHON%" (
  echo [ERROR] No se encontro Python global 3.10 en:
  echo         %PYVIDEOTRANS_PYTHON%
  echo Instala Python 3.10 global o ajusta PYVIDEOTRANS_PYTHON manualmente.
  exit /b 1
)

REM Configure HuggingFace Hub to use standard cache (required for ctranslate2)
set "HF_HOME=%USERPROFILE%\.cache\huggingface"
set "HF_HUB_CACHE=%USERPROFILE%\.cache\huggingface\hub"
set "TORCH_HOME=%USERPROFILE%\.cache\torch"

REM Aggressive-but-controlled GPU profile for production dubbing.
if "%PYVIDEOTRANS_NLLB_BATCH_LINES%"=="" set "PYVIDEOTRANS_NLLB_BATCH_LINES=256"
if "%PYVIDEOTRANS_QWEN_TTS_BATCH_LINES%"=="" set "PYVIDEOTRANS_QWEN_TTS_BATCH_LINES=12"
if "%PYVIDEOTRANS_QWEN_TTS_TORCH_THREADS%"=="" set "PYVIDEOTRANS_QWEN_TTS_TORCH_THREADS=12"
if "%PYVIDEOTRANS_FORCE_QWEN_TTS_CUDA%"=="" set "PYVIDEOTRANS_FORCE_QWEN_TTS_CUDA=1"
if "%PYVIDEOTRANS_AUTO_PROCESS_MAX_GPU%"=="" set "PYVIDEOTRANS_AUTO_PROCESS_MAX_GPU=1"
if "%PYVIDEOTRANS_PROCESS_MAX_GPU%"=="" set "PYVIDEOTRANS_PROCESS_MAX_GPU=2"

echo [INFO] PYVIDEOTRANS_PYTHON=%PYVIDEOTRANS_PYTHON%
echo [INFO] HF_HOME=%HF_HOME%
echo [INFO] PYVIDEOTRANS_NLLB_BATCH_LINES=%PYVIDEOTRANS_NLLB_BATCH_LINES%
echo [INFO] PYVIDEOTRANS_QWEN_TTS_BATCH_LINES=%PYVIDEOTRANS_QWEN_TTS_BATCH_LINES%
echo [INFO] PYVIDEOTRANS_QWEN_TTS_TORCH_THREADS=%PYVIDEOTRANS_QWEN_TTS_TORCH_THREADS%
echo [INFO] PYVIDEOTRANS_FORCE_QWEN_TTS_CUDA=%PYVIDEOTRANS_FORCE_QWEN_TTS_CUDA%
echo [INFO] PYVIDEOTRANS_AUTO_PROCESS_MAX_GPU=%PYVIDEOTRANS_AUTO_PROCESS_MAX_GPU%
echo [INFO] PYVIDEOTRANS_PROCESS_MAX_GPU=%PYVIDEOTRANS_PROCESS_MAX_GPU%
"%PYVIDEOTRANS_PYTHON%" "%ROOT_DIR%main_ui.py"
